services:
  - type: web
    runtime: image
    image:
      name: ghcr.io/mxpv/podsync
      tag: latest
    name: podsync
    plan: free
    disk:
      name: podsync-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: PORT
        value: "8080"
      - key: CONFIG_TOML
        sync: false
    startCommand: |
      echo "$CONFIG_TOML" > /app/config.toml && ./podsync --config /app/config.toml
