services:
  - type: web
    name: podsync
    env: docker
    image: ghcr.io/mxpv/podsync:latest
    plan: free

    disk:
      name: podsync-data
      mountPath: /app/data
      sizeGB: 1

    envVars:
      - key: PORT
        value: "8080"
      - key: CONFIG_TOML
        sync: false

    startCommand: |
      echo "$CONFIG_TOML" > /app/config.toml && ./podsync --config /app/config.toml
